find_package(Python3 REQUIRED)
find_package(Vulkan REQUIRED)


function(add_target_shader TARGET SOURCE DESTINATION)
	cmake_path(GET SOURCE FILENAME SHADER_FILENAME)
	set(SHADER_TARGET_NAME ${TARGET}-${SHADER_FILENAME})

	add_custom_command(OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/${DESTINATION}
			COMMAND Python3::Interpreter ${CMAKE_CURRENT_SOURCE_DIR}/share/compile_shader.py ${Vulkan_GLSLC_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE} ${CMAKE_CURRENT_SOURCE_DIR}/${DESTINATION}
			DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE}
			WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	)

	target_sources(${TARGET} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/${DESTINATION})
endfunction()
