find_package(Python3 REQUIRED)
find_package(Vulkan REQUIRED)


function(add_target_shader TARGET SOURCE DESTINATION)
	file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/shaders)

	set(SHADER_TARGET_NAME ${SOURCE})
	string(REPLACE  "/" "-" SHADER_TARGET_NAME ${SHADER_TARGET_NAME})

	set(BINARY_FILE ${CMAKE_CURRENT_BINARY_DIR}/shaders/${SHADER_TARGET_NAME}.bin)

	add_custom_command(OUTPUT ${DESTINATION}
			COMMAND Python3::Interpreter ${CMAKE_CURRENT_SOURCE_DIR}/share/compile_shader.py ${Vulkan_GLSLC_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE} ${DESTINATION}
			DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE}
			WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	)

	add_custom_target(${SHADER_TARGET_NAME}
			DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE}
	)

	add_dependencies(${TARGET} ${SHADER_TARGET_NAME})
endfunction()
